import "dotenv/config";
import express from "express";
import cors from "cors";
import { router } from "./routes";
import dbInstance from "./config/database";
const PORT = process.env.PORT || 3001;
const app = express();
app.use(cors());
app.use(router);
dbInstance.db.get('adcon');
app.listen(PORT, () => console.log(`Escuchando por el puerto ${PORT}`));